### ISSUE TITLE
[11.0] - ERROR AL GENERAR DECLARACIONES

### ISSUE THREAD

**Issue by dixgrake** [akevinieron/dgii-reports-legacy#1]
#### Impacted versions
         Ubuntu 18.04.1 LTS
         Odoo 11.0
#### Steps to reproduce
          instale el reporte luego configure el diario de los comprobantes, una vez configurado cree una
          factura de cliente con valor fiscal.
#### Current behavior
          error al generar el reporte de la dgii
#### Expected behavior
         que el reporte se pueda generar correctamente.
#### Video/Screenshot link (optional)
          traceback del error
          https://pastebin.com/e8Uxz8VQ

**Comment by dixgrake** [comment]
`<script src="https://pastebin.com/embed_js/e8Uxz8VQ"></script>`

**Comment by akevinieron** [comment]
```
File "/opt/custom/dgii-reports-legacy/models/dgii_report.py", line 813, in generate_txt_files
    company_fiscal_identificacion = re.sub(u"[^0-9]", "", self.company_id.vat)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

Este error es producido porque la compañía no tiene RNC asignado.
