### ISSUE TITLE
Utilizar Modulo

### ISSUE THREAD

**Issue by jeffryjdelarosa** [akevinieron/dgii-reports-legacy#2]
Buenas Tardes, 

Este modulo se puede utilizar y está actualizado a la nueva modalidad de la DGII y utilizarse en la version 11?

Saludos.

**Comment by akevinieron** [comment]
Hola @jjdelarosa. Estos son los reportes viejos de la dgii. Tal y como dice el nombre del repo y la descripcion del módulo:

> Este modulo agrega los reportes declarativos (anterior a mayo 2018) de la DGII basado en el módulo de localización creado originalmente por Marcos.do (Eneldo Serrata) y posteriormente mantenido por la comunidad Odoo Dominicana.

Disculpa por la confusión!

Nota: en la comunidad no existen reportes de la DGII listos para producción, al menos no gratuitos!
