### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by jeffryjdelarosa** [akevinieron/dgii-reports-legacy#3]
TypeError: Model 'dgii.report' inherits from non-existing model 'ir.needaction_mixin'

Ese es el error que tengo..

**Comment by akevinieron** [comment]
Hola @jjdelarosa. Gracias por reportar éste error. Como te comenté en el issue anterior, estos son los reportes viejos de la dgii. Tal y como dice el nombre del repo y la descripcion del módulo:

> Este modulo agrega los reportes declarativos (anterior a mayo 2018) de la DGII basado en el módulo de localización creado originalmente por Marcos.do (Eneldo Serrata) y posteriormente mantenido por la comunidad Odoo Dominicana.

Disculpa por la confusión!

Nota: en la comunidad no existen reportes de la DGII listos para producción, al menos no gratuitos!

**Comment by jeffryjdelarosa** [comment]
Gracias, Tienes algo similar me puede escribir a mi correo en el bio.. para entrar a Detalle.
